Use Node 18 and 20
zowe/zowe-cli-ftp-plugin pull request #141
Opened 2023-10-17 18:05 UTC by awharn

**What It Does**
Use node 18 and 20 in workflows

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

2023-10-17 18:27 UTC, zFernand0 requested changes
unit test failure?

2023-10-17 18:39 UTC, awharn commented
> unit test failure?

I see that, needed all the pipelines to run across all the repos to surface things like this. Kind of strange that it is only occurring on Windows, yet the same change on V1 doesn't cause the error.

2023-10-17 20:33 UTC, gejohnston approved these changes

2023-10-18 20:23 UTC, zFernand0 approved these changes
the code smell is just complaining about `thow "string"` instead of `throw new Error("string")`
not a big deal 😋 

LGTM! 😋

2023-10-19 12:29 UTC, merged